### ISSUE TITLE
ionic serve not worked

### ISSUE THREAD

**Issue by saber13812002** [candelibas/instaclone#7]
after clone to my pc

open visual studio , i cant run ionic serve

can you help me?

C:\Users\taba\Documents\GitHub\labs\instaclone>ionic serve
> ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
[app-scripts] module.js:549
[app-scripts]     throw err;
[app-scripts]     ^
[app-scripts] Error: Cannot find module 'C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\@ionic\app-scripts\bin\ionic-app-scripts.js'
[app-scripts]     at Function.Module._resolveFilename (module.js:547:15)
[app-scripts]     at Function.Module._load (module.js:474:25)
[app-scripts]     at Function.Module.runMain (module.js:693:10)
[app-scripts]     at startup (bootstrap_node.js:191:16)
[app-scripts]     at bootstrap_node.js:612:3

[INFO] Looks like @ionic/app-scripts isn't installed in this project.

       This package is required for this command to work properly.

? Install @ionic/app-scripts? Yes
> npm i -D -E @ionic/app-scripts

> node-sass@4.5.0 install C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.0 postinstall C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\node-gyp\bin\node-gyp.js
rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\taba\\Documents\\GitHub\\labs\\instaclone\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.11.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\taba\\Documents\\GitHub\\labs\\instaclone\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\taba\\Documents\\GitHub\\labs\\instaclone\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\taba\\Documents\\GitHub\\labs\\instaclone\\node_modules\\which\\which.js:80:29)\n
  at C:\\Users\\taba\\Documents\\GitHub\\labs\\instaclone\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\taba\\Documents\\GitHub\\labs\\instaclone\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\taba\\Documents\\GitHub\\labs\\instaclone\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\taba\AppData\Local\Programs\Python\Python37-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\taba\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\taba\\Documents\\GitHub\\labs\\instaclone\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\taba\Documents\GitHub\labs\instaclone\node_modules\node-sass
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\taba\AppData\Roaming\npm-cache\_logs\2018-11-14T09_13_18_871Z-debug.log
[ERROR] An error occurred while running subprocess npm.

        npm i -D -E @ionic/app-scripts exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by saber13812002** [comment]
just need to run npm install node-sass@4.7.2 --save

**Comment by saber13812002** [comment]
just need to remove node_module folder

run visual studio code as administrator

and remove json_lock

then npm i

ionic serve


then need to :+1: 


https://stackoverflow.com/a/44988493/308578

**Comment by tifannyknox** [comment]
npm install @ionic/app-scripts@latest
